
version: '3.3'

services:
  db:
    image: postgres
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    links:
      - db:db
    depends_on:
      - db
# version: '2'
#
# services:
#   data:
#     build: ./
#     env_file: .env
#     volumes:
#         - /var/lib/postgresql
#         - ./createdb.sh:/docker-entrypoint-initdb.d/createdb.sh
#     command: "true"
#
#   web:
#     restart: always
#     build: .
#     expose:
#       - "8000"
#     links:
#       - postgres:postgres
#     env_file: .env
#     volumes:
#       - ./web:/data/web
#     command: >
#       bash -c "python manage.py migrate
#       && python ./manage.py collectstatic --noinput
#       && python manage.py runserver 0.0.0.0:8000"
#
#   postgres:
#     restart: always
#     image: postgres:latest
#     volumes_from:
#       - data
#     ports:
#       - "5432:5432"
