version: 2
jobs:
  build:
    working_directory: ~/django_blog
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - run:
          name: install testing dependencies
          command: |
            sudo pip install -r ./requirements.txt
      - run:
          name: list installed packages
          command: |
            sudo pip freeze
      - run:
          name: collect static files
          command: |
            python ./manage.py collectstatic --noinput

      # run tests!
      - run:
          name: run tests
          command: |
            tox
